

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/auth-service
        username: root
        password: password
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
server:
  port: 8080

openapi:
    service:
        server: http://localhost:${server.port}
        title: Keycloak Admin API
        version: 1.0.0
        description: API Documentation for Keycloak Admin Service
springdoc:
    swagger-ui:
        query-config-enabled: false
    api-docs:
        path: /api-docs-json

keycloak:
  url: http://localhost:8081/realms/edu-school
  login-url: http://localhost:8081/realms/edu-school/protocol/openid-connect/token
  client-secret: WDFIqQVxnWTLAHwudjWxzwxfpCZEJ4VN