spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth-service
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/auth/realms/edu-school
#       opaquetoken:
#          client-id:
#          client-secret:
#          introspection-uri:
#  jwt or opquetoken
server:
  port: 8080

openapi:
  service:
    server: http://localhost:${server.port}
    title: Keycloak Admin API
    version: 1.0.0
    description: API Documentation for Keycloak Admin Service
springdoc:
  swagger-ui:
    query-config-enabled: false
  api-docs:
    path: /api-docs-json

keycloak:
  client-secret: YyupQFGJp4OPF99XZDKjq9rgpfL4aD5B
